# docker-compose file created just for scaling the application in the future
version: "3.5"

services:
  express-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4242:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    env_file:
      - .env
    restart: on-failure
